# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('usr', '0002_remove_empleado__empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='uempleado',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empleado'),
            preserve_default=False,
        ),
    ]
