# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0003_empleado_uempleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='_empresa',
            new_name='uempresa',
        ),
    ]
